# -*- coding: utf-8 -*-

#This is a setup.py script generated by py2applet
#
#Usage:
#    python setup.py py2app


from setuptools import setup

APP = ['mapit.py']
APP_NAME = 'Mapit'
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'mapit.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': 'Search address from clipboard',
        'CFBundleIdentifier': 'com.codyjking.osx.mapit',
        'CFBundleVersion': '1.0',
        'CFBundleShortVersionString': '1.0',
        'NSHumanReadableCopyright': u'Copyright © 2017, Cody King'
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
